### ISSUE TITLE
Not wokring on Mac

### ISSUE THREAD

**Issue by MaxBec** [jziolkowski/tdm#50] opened 2019-11-06 10:55 UTC
Followed the instructions but tool is not starting up on mac.

**Comment by jziolkowski** [comment] 2019-11-06 10:55
I'm not a wizard, you need to post some error messages so I can see what the problem is.

**Comment by MaxBec** [comment] 2019-11-06 10:56
Where are the log files located?

**Comment by jziolkowski** [comment] 2019-11-06 10:57
When you start TDM from the console it should leave you a backtrack of the error

**Comment by MaxBec** [comment] 2019-11-06 10:58
Nope it doesnt. There is just the python rocket hopping in the applications bar. And then it says its not reposnding anymore.

**Comment by jziolkowski** [comment] 2019-11-06 10:59
Like I said, start the console, go to the TDM directory, and start it from there

**Comment by MaxBec** [comment] 2019-11-06 11:00
Thats exactly what i am doing:
With python3 tdm.py

**Comment by jziolkowski** [comment] 2019-11-06 11:00
and in the terminal it doesn't leave any error message?

**Comment by MaxBec** [comment] 2019-11-06 11:03
Nope.

**Comment by MaxBec** [comment] 2019-11-06 11:08
Do you have any idea how to fix this?

**Comment by jziolkowski** [comment] 2019-11-06 11:09
Join our discord server. There are Mac users reporting TDM works. Since I don't have a Mac, I really can't help here.

**Comment by jziolkowski** [comment] 2019-11-20 19:01
Closing as support has been provided on Discord

**Closed by jziolkowski** 2019-11-20 19:01 UTC
