### ISSUE TITLE
culumn FriendlyName not visible 

### ISSUE THREAD

**Issue by spedruzzo** [jziolkowski/tdm#204] opened 2022-09-01 22:24 UTC
I have windows version 0.2.11 but FriendlyName column not visible, I tried to add in cfg file, now is visible but empty (also after a restart of the device)

**Comment by barbudor** [comment] 2022-09-02 17:28
There is no way to display a FriendlyName column
The way TDM is working, 
- If DeviceName is defined, DeviceName is displayed in the "Device" column
- If DeviceName is not defined and FriendlyName1 is defined, then FriendlyName1 is displayed in the "Device" column
- If any of DeviceName nor FriendlyName1 is defined, then the %topic% is displayed in the "Device" column

This is how it is

**Comment by spedruzzo** [comment] 2022-09-05 16:30
ok, I can change my naming convention no problem, but I cannot understand why this restriction, will be nice to have both field configurable in cfg file, anyway thanks for answer

**Comment by barbudor** [comment] 2022-09-05 21:05
You still open a feature request but the author has very little time for improvement

**Comment by jerrymjones** [comment] 2022-09-24 16:00
Hmmm, On Linux nothing is displayed under the "Device" column. I have both DeviceName and FriendlyName1 defined.

**Comment by barbudor** [comment] 2022-09-24 20:12
Indeed, same problem on Ubuntu 22.04 with same packages as on Windows, but works fine on Windows
No idea how to address that

**Comment by jerrymjones** [comment] 2022-09-25 16:14
I'm not a Python guru so take this with a grain of salt. The problem seems to be line 280 in models.py. The calculation results in a float but the next function where it's used needs an int.

I edited /home/<user>/.local/lib/python3.10/site-packages/Util/models.py

and change line 280 from

px_y = (option.rect.height() - 24) / 2

to

px_y = (int)((option.rect.height() - 24) / 2)

and it works. May not be the right answer but for now I'm happy. :-)

**Comment by jerrymjones** [comment] 2022-09-25 17:51
#196 probably already addresses this issue.

**Comment by barbudor** [comment] 2022-09-25 19:29
I confirm it solve the issue on Ubuntu 22.04

@jziolkowski Could you please kindly merge PR #197 ?

**Comment by jziolkowski** [comment] 2022-11-16 16:48
merged and released :)

**Closed by jziolkowski** 2022-11-16 16:48 UTC

**Comment by jerrymjones** [comment] 2022-11-16 16:52
Thank you!

Jerry

**Comment by barbudor** [comment] 2022-12-13 21:06
Looks like the problem is back on develop branch on Lubuntu 22.04
But I can't find any similar code as in master branch where this PR was applied

**Comment by barbudor** [comment] 2022-12-13 21:16
Same problem in GUI/delegates/devices.py with float divide instead of integer device

However fixing it is not enough to solve the situation, so not worth a PR for now:

![image](https://user-images.githubusercontent.com/2996042/207445216-fa5a244c-2f82-4079-a51b-c928b51f6c29.png)
