### ISSUE TITLE
TDM 0.25 EXE

### ISSUE THREAD

**Issue by scargill** [jziolkowski/tdm#61] opened 2019-12-07 11:15 UTC
I just grabbed the latest TDM (I'm on Windows 10 64 bit) - I don't know if this is new but on powering up TDM (after waiting a few minutes) it does not seem to know the on-off status of most of my Sonoff devices... and on right-clicking in the devices list to bring up the WebUI for a device, where most seem fine, at least one of them comes back with "This site cannot be reached" even though keyng its name into a browser pulls up the web ui no problem. http://my-bed-heater.broadband/

**Comment by jziolkowski** [comment] 2019-12-07 11:52
Pete,
the power state is due to a change in Tasmota, which is now being reverted. Please see <https://github.com/arendst/Tasmota/issues/7125#issuecomment-562779351>.

As for "This site cannot be reached" issue it is also outside TDM - the WebUI component is just an ordinary Chromium browser. If it can't access your devices then any other browser can't also. I've see n that happen with Tasmota devices every now and then.

**Comment by jziolkowski** [comment] 2019-12-07 17:41
The issue has been fixed in latest dev bins. Closing as the issue is solved.

**Closed by jziolkowski** 2019-12-07 17:41 UTC

**Comment by scargill** [comment] 2019-12-07 20:12
The EXE file still says v0.25 and looks like it was updated yesterday (Friday). Can you clarify? Latest dev bins of Tasmota?

**Comment by jziolkowski** [comment] 2019-12-07 20:24
Yes, Tasmota uses .bin files, not TDM

**Comment by scargill** [comment] 2019-12-07 21:04
Yep, got that thanks. As far as I'm aware I have only one Sonoff BASIC that us stuck... I can't easily serial pogram it so I'm waitin o see if a Tasmots a7.1.2.3 appears, Theo said something about an update - but it looks to me like we're still on 7.1.22 here - http://thehackbox.org/tasmota/tasmota.bin - I think a glass of wine is in order....
