### ISSUE TITLE
Rules length not in line with latest Tasmota limits 

### ISSUE THREAD

**Issue by cluelesscris** [jziolkowski/tdm#121] opened 2021-01-16 19:15 UTC
Rules can now be at least 1000 characters - TDM limits users to 480.

Since compression was added and improved the length of a rule set can be 'at least 1000 characters' - quoting from the Tasmota documentation.  

Can the limit in TDR be increased accordingly?

Thanks

**Comment by eku** [comment] 2021-01-17 10:47
I ask to take into account that older versions have other limits and should still be supported.

**Comment by Jason2866** [comment] 2021-01-17 12:42
Rules max size is not a fixed value anymore. It uses a compression algo (when needed) which has to be implemented in TDM.

**Comment by Jason2866** [comment] 2021-01-17 12:43
Duplicate of #93

**Closed by Jason2866** 2021-01-17 12:43 UTC
