### ISSUE TITLE
Windows 11 - Devices not shown

### ISSUE THREAD

**Issue by chivas03** [jziolkowski/tdm#212] opened 2022-12-11 20:59 UTC
Dear All,

I used TDM until now at my laptop with WIN7 - everything works fine! 
Few days ago I needed a got my new laptop with WIN 11.
I tried to move TDM to my new device - I installed Phyton and Mosquito - but I am not able to get any device in the overview.
TDM connects to the Broker but nothings happens. Is there any suggestion what to do or Log-file available?

Regards
Marco

**Comment by jziolkowski** [comment] 2022-12-11 21:00
Did you remember to set discovery patterns in TDM?

**Comment by chivas03** [comment] 2022-12-11 21:08
Yes, I set same discovery pattern as I had previously

**Comment by jziolkowski** [comment] 2022-12-11 21:09
open your tdm config file and in the general section add (or change) DEBUG=1. Restart TDM and check the logs

**Comment by chivas03** [comment] 2022-12-11 21:22
Where or how can I find the config file - I just have the file "tdmgr_0.2.13" in a folder and nothing else is or will be generated

**Comment by jziolkowski** [comment] 2022-12-11 21:25
it's in `<your user directory>\TDM\tdm.cfg`

**Comment by jziolkowski** [comment] 2022-12-11 21:46
it doesn't show any extra discovery patterns other than default. Can you paste an example fulltopic from a few of your devices?

**Comment by chivas03** [comment] 2022-12-11 22:02
so far I just use the standard fulltopic from Tasmota ( %prefix%/%topic%/ )

**Comment by jziolkowski** [comment] 2022-12-11 22:05
can you compare old config file with the new one?

**Comment by chivas03** [comment] 2022-12-11 22:17
I compared it, just see diferences in the window_geometry entry. I tried to use the old config file as well, but didn't change anything

**Comment by barbudor** [comment] 2022-12-11 22:18
I have a brand new PC running Windows 11 and I have no problem running TDM, either the pre-built executable  tdmgr_0.2.13.exe or the python one

I wonder why did you installed mosquitto on the laptop ? SHouldn't it be running on some fixed infrastructure like a rapspi or a server ?
If you connect TDM to a MQTT broker on your laptop but have the Tamsota connected to another broker, nothing is going to happen

**Comment by jziolkowski** [comment] 2022-12-11 22:19
so the issue must be elsewhere. Stupid question, but are you connecting to the same MQTT server that your devices?

**Comment by chivas03** [comment] 2022-12-11 22:44
I use the same MQTT server addresses. I guess the issue could be with my local broker tool or any restriction from Windows side.

@barbudor : I do not need any MQTT broker for my home applications. At the moment I can do everything I want with Tasmota and WEBSEND commands and Rules.

However, I saw that an MQTT Broker App was available for my smart phone and I configured TDM and a device for that server --> The device got visible within TDM. Strange behavior of my system.

As soon as I move on with the problem identification/solution, I will share the results.

Thanks.

**Comment by jziolkowski** [comment] 2022-12-11 22:46
I'm quite confused with what you are trying to achieve with using a MQTT broker and not needing one for your home applications :) Either way good luck with solving that; and pls do drop me a line here, I'm very intrigued :D

**Comment by CaptClaude** [comment] 2022-12-14 05:21
At the risk of getting my hand slapped, I'm going to say that I have the same issue: TDM installed, runs, no devices displayed.
Not with Win11 rather MacOS 10.14.6 with. Python 3.9.2 installed.  Ran `pip install PyQt5==5.14.2` after farting around with other versions and learning TDM wants that version.  Installed `paho-mqtt` before I understood I should point TDM to the same broker as my devices use.  Installed and uninstalled `pyqtwebengine` because it wants a higher version of PyQT5 than TDM.
Starts, runs, opens window. Buttons click, I can set up my broker.  I use standard patterns so that is not an issue.
Added `DEBUG=-1` to `tdm.cfg` which contains this:

```
[General]
DEBUG=1
connect_on_startup=true
hostname=broker.local
password=
port=1883
username=
version=0.2.11
views_order="Home;Health;Firmware;Wifi;MQTT"
window_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1'\0\0\0z\0\0\a\xd0\0\0\x4O\0\0\x1'\0\0\0\x90\0\0\a\xd0\0\0\x4O\0\0\0\0\0\0\0\0\n\0\0\0\x1'\0\0\0\x90\0\0\a\xd0\0\0\x4O)

[Views]
Firmware="Version;Core;SDK;ProgramSize;Free;OtaUrl"
Health="Uptime;BootCount;RestartReason;LoadAvg;Sleep;MqttCount;LinkCount;Downtime;RSSI"
Home="Module;Power;Color;LoadAvg;LinkCount;Uptime"
MQTT="Topic;FullTopic;CommandTopic;StatTopic;TeleTopic;FallbackTopic;GroupTopic"
Wifi="Hostname;Mac;IPAddress;Gateway;SSId;BSSId;Channel;RSSI;LinkCount;Downtime"
```

Status line says I am connected to my broker.
tdm.log shows this:

```
2022-12-13 22:58:03 [INFO] ### TDM START ###
2022-12-13 22:58:06 [INFO] MQTT: Subscribed to tele/#, stat/#, cmnd/#, +/tele/#, +/stat/#, +/cmnd/#
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/porch/lites1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/porch/lites2/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/sonoff/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites3/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites4/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites2/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/Christmas1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/Liteswitch1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/Liteswitch2/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites5/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallClick2/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallWart1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallWart2/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/tero/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/FrontPorch/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/washer/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/dryer/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallWart3/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/house/Lites4/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/home/Liteswitch1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/home/washer/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/3D/E5.1/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_55AFBA/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_00647E/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/WallWart2_00647E/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_006046/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/WallWart1_006046/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_07660F/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/WallWart3/LWT
2022-12-13 22:58:06 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_A7CA0F/LWT
```
So clearly something is happening.
Here is a view of my devices/topics using MQTT Explorer:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/19495272/207511366-1d98ad4f-c8b9-442c-9582-70c30df0ad67.png">

All of my devices are >Tasmota 11 (Most are 12+).
Here is the configuration of the first device in the log above:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/19495272/207511942-971c652a-3d4a-4880-988c-4b1849ca3b9f.png">

Feel free to tell me to create a new issue but maybe what I provided will help @chivas03 with what he needs to tell you so you can help him.

Any suggestions?

Thanks!

**Comment by CaptClaude** [comment] 2022-12-14 16:04
Installed with **pip** (which I had upgraded immediately prior) which installed `version=0.2.11` (per the log). 
```
Bardolino:~ jm$ pip install tdmgr
Requirement already satisfied: tdmgr in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.2.11)
Requirement already satisfied: paho-mqtt>=1.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from tdmgr) (1.6.1)
Requirement already satisfied: PyQt5==5.14.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from tdmgr) (5.14.2)
Requirement already satisfied: PyQt5-sip<13,>=12.7 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from PyQt5==5.14.2->tdmgr) (12.11.0)
Bardolino:~ jm$ tdmgr.py
```
...then the window appears.

I will admit that the Python install/uninstall process is a bit of a mystery to me, but `pip uninstall tdmgr` uninstalled 0.2.11.

I just looked - didn't realize there was a pre-built OS X app (0.2.13).  Downloaded and opened.

Still no devices showing in the window but the log is appended to and shows the same as above, It read the cfg file and connected to the broker.  Deleted the old cfg file and restarted, adding the broker.  Connects. No devices.  Added `DEBUG=1` to cfg file.  Log looks the same as before.

**Comment by barbudor** [comment] 2022-12-14 20:41
I don't have Mac, only Win10, 11 and Lubuntu 22.04
But I can run either the prebuilt exe for 0.2.13 or the python from the Git
Installing from pip is unsuccessfull on Windows (cannot build sip but that's independant from TDM)
Will test Lubuntu later

**Comment by jziolkowski** [comment] 2022-12-14 20:43
0.2.11 is outdated, can you please try the latest develop?

**Comment by jziolkowski** [comment] 2022-12-14 20:44
Also, first of all, you don't have autodiscovery patterns configured and I see you use custom topics

**Comment by barbudor** [comment] 2022-12-14 20:47
He still have some devices with standard FullTopic so those should appear
Didn't noticed but with 0.2.11 it's probably before the patch on the integer divide
So that's likely to be the cause

**Comment by jziolkowski** [comment] 2022-12-14 20:52
I'm launching action to build latest develop: https://github.com/jziolkowski/tdm/actions/runs/3698622046

In a few mins there will be a zip file available at the bottom of the page, all builds are there. Get it, open, test the exe and let us know.

And for the future please create your own issue. It's easier to mark a duplicate than to browse thorough messages of various people discussing possibly unrelated problems ;)

**Comment by Jason2866** [comment] 2022-12-14 21:19
@CaptClaude How have you installed PyQt? My experience, only installing via brew resulted in a working PyQt5. Maybe this is M1 specific.

**Comment by Jason2866** [comment] 2022-12-14 21:23
@jziolkowski Build fails with Windows

**Comment by jziolkowski** [comment] 2022-12-14 23:49
_sigh_ fixed python version in CI actions, now it went ok.

Latest build available at https://github.com/jziolkowski/tdm/actions/runs/3699690844

**Comment by CaptClaude** [comment] 2022-12-15 04:47
> 0.2.11 is outdated, can you please try the latest develop?

I did after reporting installing 0.2.11 -- no devices displayed.

> Latest build available at https://github.com/jziolkowski/tdm/actions/runs/3699690844
Downloaded, extracted, starts then dies without ever opening a window or writing a cfg or log file.  File version has the same number as the one that runs but does not show any devices.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/19495272/207772014-3fb3dbf7-334f-48a0-b72d-d43efe0a2da2.png">

The _official_ build downloaded previously (0.2.13) did not crash but showed no devices.

>@CaptClaude How have you installed PyQt?

Ran `pip install PyQt5==5.14.2` because TDM says that's the version it wants (would like confirmation on this).
Also, I am still on 10.14.6 (Mojave) and Brew chastises me for not being beyond that (no longer supported). I tried but it failed. Which is just as well because it _is_ installed.
What's installed?
```
Bardolino:~ jm$ pip list
Package           Version
----------------- -----------
bezier            2021.2.12
certifi           2020.12.5
freetype-py       2.1.0.post1
numpy             1.20.1
paho-mqtt         1.6.1
pip               22.3.1
PyPrind           2.11.3
PyQt5             5.14.2
PyQt5-Qt5         5.15.2
PyQt5-sip         12.11.0
PyQtWebEngine-Qt5 5.15.2
pyserial          3.5
setuptools        49.2.1
svgelements       1.0.2
svgpathtools      1.3.3
svgwrite          1.4
xmodem            0.4.6
```
Is there something wrong with these two?
```
PyQt5-Qt5         5.15.2
PyQtWebEngine-Qt5 5.15.2
```
I uninstalled `PyQt5-Qt5` and `PyQtWebEngine-Qt5 5.15.2` and there was no change of behavior.  Now I have this:
```
Bardolino:~ jm$ pip list
Package      Version
------------ -----------
bezier       2021.2.12
certifi      2020.12.5
freetype-py  2.1.0.post1
numpy        1.20.1
paho-mqtt    1.6.1
pip          22.3.1
PyPrind      2.11.3
PyQt5        5.14.2
PyQt5-sip    12.11.0
pyserial     3.5
setuptools   49.2.1
svgelements  1.0.2
svgpathtools 1.3.3
svgwrite     1.4
xmodem       0.4.6
```
Clearly I am guilty of thread highjacking here.

**Comment by jziolkowski** [comment] 2022-12-15 11:09
So, as for develop, the PyQtWebengine is no longer needed, so you can ditch that one.

Next, try running TDM with the following command line flags: `--debug --local`

Assuming that the Mac bundle passes params to the executable, this should result with log file being created in the local directory

**Comment by CaptClaude** [comment] 2022-12-16 04:11
The most recent development branch (shown in the screenshot above), starts and then exits.
```
Bardolino:dist jm$ ls -las
total 55360
    0 drwxr-xr-x@ 4 jm  staff       128 Dec 14 22:16 .
    0 drwxr-xr-x  8 jm  staff       256 Dec 14 22:16 ..
    0 drwxr-xr-x@ 3 jm  staff        96 Dec 14 17:48 tdmgr-macOS.app
55360 -rwxr-xr-x@ 1 jm  staff  28343168 Dec 14 17:48 tdmgr_0.2.13
Bardolino:dist jm$ open ./tdmgr-macOS.app --args --debug --local
```
If I delete the log file, it does not create a new one.

I can use the same command line in a different directory and run the most recent _release_ and I get a log file:
```
2022-12-15 22:08:27 [INFO] ### TDM START ###
2022-12-15 22:08:29 [INFO] MQTT: Subscribed to tele/#, stat/#, cmnd/#, +/tele/#, +/stat/#, +/cmnd/#
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/porch/lites1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/porch/lites2/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/sonoff/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites3/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites4/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites2/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/Christmas1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/Liteswitch1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/Liteswitch2/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/lites5/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallClick2/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallWart1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallWart2/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/tero/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/FrontPorch/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/washer/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/dryer/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/WallWart3/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/house/Lites4/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/home/Liteswitch1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/home/washer/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/3D/E5.1/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_55AFBA/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_00647E/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/WallWart2_00647E/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_006046/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/WallWart1_006046/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_07660F/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/WallWart3/LWT
2022-12-15 22:08:30 [INFO] DISCOVERY: LWT from an unknown device tele/tasmota_A7CA0F/LWT
```

One observation:  The version that runs pops up an icon in the dock which disappears and then reappears.  The version that doesn't run pops up an icon which disappears and does not reappear (also no program window).

What else can I do to help debug this?

**Comment by jziolkowski** [comment] 2022-12-16 12:31
When using the command line flags, do you see tdm.cfg created in the same directory? If not, and the log file is missing, then the args are not passed correctly. 

By last release you mean the develop I built manually, yes?

**Comment by jziolkowski** [comment] 2022-12-16 12:32
Also, the command line flags are supported only in the develop version; for the previous version you need to manually add DEBUG=1 to tdm.cfg file (should be located in TDM directory in your home dir)

**Comment by CaptClaude** [comment] 2022-12-19 03:33
I have been trying different scenarios and have failed to find one where the develop version does not die.

> By last release you mean the develop I built manually, yes?

Yes. And you are correct that the command line args are not getting passed to the app properly (or at all). I have tried every permutation of the `open` command in OS X and the `--debug --local`  is not passed to the program. Or if it is, I can't tell because it dies immediately.  With or without the arguments, with or without the `-a`, I get a brief flash of an icon in the dock and then it goes away. No log or cfg file are created.  With the release version, I get a brief icon in the dock which goes away and then returns. I get the feeling the first icon is a launcher trying to launch the file not named .app but that's just an uneducated guess. 

I'm out of guesses.

**Comment by jziolkowski** [comment] 2022-12-19 11:18
ok, so my only suggestion right now is to install the venv with requirements and try running the code cloned directly from the repo. Since I don't own a Mac, maybe @Jason2866 would be kindly able to support with the steps needed to install

**Comment by Jason2866** [comment] 2022-12-19 17:26
Sorry since MacOS 10.14.6 is quiet old, i cant help this version is so different to actual ones. `brew` afaik is not working/supported there. It can be a config hell to get stuff running without `brew`. GH actions cant be used either for testing since this version isnt available anymore there too.

**Comment by CaptClaude** [comment] 2022-12-20 15:41
@Jason2866 I know I am old. I have an MBP that I will start bringing up to speed over the next few weeks for testing. I have a couple of apps that will certainly break if I just bump up to Ventura, so I will take it one step at a time. And yes, Brew does not work with Mojave - I get dire warnings that I am on my own.
 
@jziolkowski thanks for taking the time to do this for me. Take your time, I will be out of town starting tomorrow until after New Years. No rush...

Happy Holidays to all.

**Comment by chivas03** [comment] 2023-01-05 16:35
> I'm quite confused with what you are trying to achieve with using a MQTT broker and not needing one for your home applications :) Either way good luck with solving that; and pls do drop me a line here, I'm very intrigued :D

Tasmota covers a lot of tasks (websend, pulsetime, rules, etc...) and with three kids I do not have enough spare time to set-up a proper home server so far ;-)

**Comment by chivas03** [comment] 2023-01-05 16:44
> so the issue must be elsewhere. Stupid question, but are you connecting to the same MQTT server that your devices?

I could identify and fix my mistake --> It was related to my local setup as OpenSSL was missiing:

* OpenSSL
    Link: http://slproweb.com/products/Win32OpenSSL.html
    Install "Win32 OpenSSL 1.1.0* Light" or "Win64 OpenSSL 1.1.0* Light"
    Required DLLs: libssl-1_1.dll, libcrypto-1_1.dll or libssl-1_1-x64.dll, libcrypto-1_1-x64.dll

Please ensure that the required DLLs are on the system path, or are in the same directory as
the mosquitto executable - usually C:\Program Files (x86)\mosquitto or C:\Program Files\mosquitto.

And I used mosquito 1.6.9 instead of 2.0.15

Thanks for the support

**Comment by jziolkowski** [comment] 2023-01-13 15:56
So it's an issue of you configuring mosquitto, yes?

**Comment by chivas03** [comment] 2023-01-15 19:45
> 

Yes, sorry for inconvenience

**Comment by jziolkowski** [comment] 2023-01-15 20:08
No problem, glad the root issue has been found.

**Closed by jziolkowski** 2023-01-15 20:08 UTC
Labels: awaiting feedback
